{
 "title": "Distributed Rate Limiter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(jvm_memory_used_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  rate(\r\n    redis_latency_seconds_bucket[5m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Decision Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  rate(\r\n    rate_limit_decision_latency_seconds_bucket[5m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejection Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n rate(requests_blocked_total[1m])/\r\n rate(requests_total[1m])\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(requests_blocked_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allowed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(requests_allowed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Requests (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "rate(requests_total[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}